"""FFmetadata chapter-file generation for M4B audiobooks.

An M4B file stores chapters as timestamped metadata inside a single MP4
container.  FFmpeg reads these from an *FFmetadata* text file passed as a
second input with ``-map_metadata``.  This module builds that file.

The FFmetadata format is documented at
https://ffmpeg.org/ffmpeg-formats.html#Metadata — the leading
``;FFMETADATA1`` line is required, and the characters ``=``, ``;``, ``#`` and
``\\`` (plus a literal newline) must be escaped with a backslash inside keys
and values.
"""

from __future__ import annotations

from pathlib import Path

from epub2audio.models import BookMetadata, ChapterMarker
from epub2audio.utils.files import atomic_write

# Timebase denominator for chapter offsets (offsets are in milliseconds).
_TIMEBASE = "1/1000"


def _escape(value: str) -> str:
    """Escape FFmetadata special characters in a key or value.

    Backslash is escaped first so escapes added for other characters are not
    themselves re-escaped.  Newlines are escaped so a multi-line title cannot
    prematurely terminate the entry.

    Args:
        value: Raw key or value string.

    Returns:
        The escaped string safe to embed in an FFmetadata file.
    """
    value = value.replace("\\", "\\\\")
    for ch in ("=", ";", "#"):
        value = value.replace(ch, "\\" + ch)
    return value.replace("\n", "\\\n")


def write_ffmetadata_chapters(
    markers: list[ChapterMarker],
    book: BookMetadata,
    out_path: Path,
) -> None:
    """Write an FFmetadata file describing book tags and chapter markers.

    The resulting file is intended to be passed to FFmpeg as an input and
    referenced with ``-map_metadata`` when muxing the final ``.m4b``.

    Args:
        markers: Ordered chapter markers with millisecond start/end offsets.
            May be empty (only book-level tags are written).
        book: Book metadata used to populate album/artist/genre tags.
        out_path: Destination path for the FFmetadata file.  Written atomically.

    Raises:
        OSError: If the file cannot be written.
    """
    lines: list[str] = [";FFMETADATA1"]

    # Book-level tags (album == book title for audiobook players).
    lines.append(f"title={_escape(book.title)}")
    lines.append(f"album={_escape(book.title)}")
    lines.append(f"artist={_escape(book.author)}")
    lines.append(f"album_artist={_escape(book.author)}")
    lines.append("genre=Audiobook")
    if book.date:
        lines.append(f"date={_escape(book.date)}")
    lines.append("comment=Generated by epub2audio")

    for marker in markers:
        lines.append("[CHAPTER]")
        lines.append(f"TIMEBASE={_TIMEBASE}")
        lines.append(f"START={marker.start_ms}")
        lines.append(f"END={marker.end_ms}")
        lines.append(f"title={_escape(marker.title)}")

    content = ("\n".join(lines) + "\n").encode("utf-8")
    atomic_write(out_path, content)
