"""FFmpeg ID3 tag and cover-art embedding for epub2audio.

All FFmpeg calls use argument arrays — ``shell=True`` is **never** used.
The MP3 is rewritten atomically via a ``.tmp`` sidecar.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

from epub2audio.models import BookMetadata
from epub2audio.utils.subprocess import run_command


def embed_metadata(
    mp3_path: Path,
    metadata: BookMetadata,
    track_number: int,
    total_tracks: int,
    chapter_title: str,
    cover_bytes: bytes | None = None,
) -> None:
    """Embed ID3 tags and optional cover art into an MP3 file.

    Reads *mp3_path*, adds the requested ID3 tags (and optionally an attached
    picture), and writes the result atomically back to *mp3_path* via a
    ``.tmp`` sidecar renamed with :func:`os.replace`.

    Args:
        mp3_path: Path to the existing MP3 file to annotate.
        metadata: :class:`~epub2audio.models.BookMetadata` for the source book.
        track_number: 1-based chapter index (written as ``"N/total"``).
        total_tracks: Total number of chapters in the audiobook.
        chapter_title: Title of this specific chapter (written as ``title`` tag).
        cover_bytes: Raw image bytes (JPEG or PNG) to embed as cover art, or
            ``None`` to skip cover embedding.

    Raises:
        MissingDependencyError: If ``ffmpeg`` is not on ``PATH``.
        subprocess.CalledProcessError: If FFmpeg exits with a non-zero code.
        OSError: If temporary files cannot be created or the rename fails.
    """
    tmp_path = mp3_path.with_suffix(mp3_path.suffix + ".tmp")
    cover_tmp: str | None = None

    try:
        metadata_args = [
            "-metadata",
            f"title={chapter_title}",
            "-metadata",
            f"album={metadata.title}",
            "-metadata",
            f"artist={metadata.author}",
            "-metadata",
            f"album_artist={metadata.author}",
            "-metadata",
            f"track={track_number}/{total_tracks}",
            "-metadata",
            "genre=Audiobook",
            "-metadata",
            "comment=Generated by epub2audio",
        ]
        if metadata.date:
            metadata_args += ["-metadata", f"date={metadata.date}"]

        if cover_bytes is not None:
            # Write cover to a temp file so FFmpeg can read it as a second input
            fd, cover_tmp = tempfile.mkstemp(suffix=".jpg")
            try:
                os.write(fd, cover_bytes)
            finally:
                os.close(fd)

            args = [
                "ffmpeg",
                "-y",
                "-i",
                str(mp3_path),
                "-i",
                cover_tmp,
                "-map",
                "0:a",
                "-map",
                "1:v",
                "-c:a",
                "copy",
                "-c:v",
                "copy",
                "-id3v2_version",
                "3",
                *metadata_args,
                "-f",
                "mp3",
                str(tmp_path),
            ]
        else:
            args = [
                "ffmpeg",
                "-y",
                "-i",
                str(mp3_path),
                "-c",
                "copy",
                "-id3v2_version",
                "3",
                *metadata_args,
                "-f",
                "mp3",
                str(tmp_path),
            ]

        run_command(args)
        os.replace(tmp_path, mp3_path)

    except Exception:
        Path(tmp_path).unlink(missing_ok=True)
        raise
    finally:
        if cover_tmp is not None:
            try:
                os.unlink(cover_tmp)
            except OSError:
                pass
